### ISSUE TITLE
Support markdown

### ISSUE THREAD

**Issue by fox0430** [fox0430/moe#415]

**Comment by kevinmatthes** [comment]
@fox0430

I am about to take a look at that.  In order to suggest a sane initial setup, I would need to know how to colour Markdown headings.  How about `gtBuiltin`?  In the first setup, I would only add support for hash-introduced headings as the alternative style with equals, dashes and dots is rather ReStructuredText than Markdown although both accept this markup.

Furthermore, I would like to suggest to turn YAML blocks into preprocessor instructions with respect to systems like Pandoc or even GitHub's meta data handling for issue templates and related purposes.

**Comment by fox0430** [comment]
@kevinmatthes 

About Markdown, `gtBuiltIn` is ok. And the second suggestion is interesting. Do you have any specific examples?

**Comment by kevinmatthes** [comment]
@fox0430

The second suggestion is about two different systems:  Pandoc and a GitHub feature.  I will begin with Pandoc.

Pandoc is a library for document conversion, written in Haskell and licensed GPL.  When installing the `pandoc` package on a Linux system, the CLI will be installed, as well.  With the CLI, you convert numerous document formats into each other, for instance Markdown to HTML, Microsoft Office Word to PDF, and so on.  One of my favourite conversion options is Markdown to PDF using LaTeX.  Sometimes, you need a LaTeX-rendered PDF but the effort for a whole LaTeX preamble is too much for some ten pages (very detailed configurations can demand a thousand lines and more; putting those configurations into LaTeX packages, on the other hand, would require the specification of an insane number of options).  Pandoc will accept your Markdown document(s) for input and compile it into a PDF using the LaTeX ecosystem.  But the results without any further options often do not meet all requirements, for example page margins.  Thus, you can specify your LaTeX settings using YAML -- either at the top of the source file or as a file on its own to be input before the actual Markdown text.  In most cases, there are no differences since many LaTeX commands are allowed.  (I still did not find out how to load further packages.  But AMS TeX works fine and out of the box.)  Even presentations are possible!  Due to the role of the YAML settings acting as settings for Pandoc, they are comparable to C's preprocessor.

The second system is a GitHub feature.  Large projects often organise their issues with templates or the newer YAML forms.  (If you are interested, I can configure YAML forms because there are more features available than with templates; see https://github.com/kevinmatthes/git-aliases-f18/tree/main/.github/ISSUE_TEMPLATE for examples.)  Templates allow for the specification of meta data such as assignees, labels, and so on.  Again, the YAML block controls settings and can be thus considered preprocessor instructions; see https://github.com/citation-file-format/citation-file-format/tree/main/.github/ISSUE_TEMPLATE for examples.

**Comment by fox0430** [comment]
@kevinmatthes 

Thank you for the explanation.
Pandoc is a very interesting tool. But I don't enough understand what we need to add to moe.
What do you want to add a feature to moe? or what do you want to do on moe?
Do you know any editors or tools that already do what you want?

**Comment by kevinmatthes** [comment]
@fox0430

A syntax highlighting for Markdown requires to add / modify the following features:

1. modify hash lexer (Markdown headings which are introduced by `#` characters)
2. add comment lexer for `<!-- -->` comments (Markdown shares this type with HTML, CSS, XML, and SVG -- but only SVG rejects `--` within a comment)
3. add lexer for `--- ---` fields (Markdown YAML blocks)
4. add lexer for both bold markups
5. add lexer for both italic markups
6. add lexer for all three source code markups (inline, block, and -- somehow more difficult -- indentation)

And these are the points I would like to add for Pandoc support:

1. add lexer for LaTeX formulas
2. add lexer for LaTeX macros

Most of these points are reusable for other languages, so I would prefer to add them one by one in order to also enable additions to other already supported languages.

As a reference editor for Markdown support, I mostly focus on `mcedit` (part of the Midnight Commander, `mc` Linux package).  I also compare my results to Zee (Rust binary from sources:  https://github.com/zee-editor/zee) and `ne` (Linux package).

I would begin with the comments and headings.

**Comment by fox0430** [comment]
@kevinmatthes 

Okay, I understand. thank you.
It looks good.

**Comment by kevinmatthes** [comment]
@fox0430

I am debugging my current solution at the moment and I had been wondering why the highlighting of trailing whitespaces (TWS) in Markdown is disabled.

**Comment by kevinmatthes** [comment]
@fox0430, would it be a problem if I would activate the highlighting of TWS for Markdown just as it is activated for the other languages?

**Comment by kevinmatthes** [comment]
@fox0430

I just activate it for the initial setup; turning it off again is very easy.

**Comment by fox0430** [comment]
@kevinmatthes 

Because It has meaning in Markdown. In other languages ​​it doesn't make sense so highlighting it.
But no problem enabling the highlighting of trailing spaces in Markdown if you want it.

**Comment by kevinmatthes** [comment]
@fox0430

Thank you, I did not know that TWS is meaningful in Markdown.

**Comment by kevinmatthes** [comment]
@fox0430

The current progress is as follows:

- Markdown highlighting is activated, TWS is highlighted
- comments are recognised (`gtLongComment`)
- hash headings are recognised (`gtBuiltin`)
- inline and block code sequences are recognised (`gtSpecialVar`)
- YAML settings are recognised (`gtPreprocessor`)

In my opinion, these changes are substantial enough to submit them as a PR for initial Markdown support.  I would like to suggest to turn the other points I mentioned in this issue into a new issue about enhancing the Markdown support.

Do you agree with this procedure?

**Comment by fox0430** [comment]
@kevinmatthes 

Ok. I agree. great progress!

**Comment by kevinmatthes** [comment]
@fox0430

- PR:  #1548
- list of open points:  #1549
