### ISSUE TITLE
Initial support for LSP

### ISSUE THREAD

**Issue by fox0430** [fox0430/moe#610]

**Comment by tobimensch** [comment]
I think this feature is very important and would make a huge difference.

One of the things holding me back from using moe even more often.

It needs to be implemented in a way that never blocks the user from doing his thing,
typing, making changes and so forth. So as much as possible should be delegated to
background processes, and if the user wants to do something while the whole LSP/highlighting/
autocompletion stuff is not yet up to speed, then moe needs to simply interrupt it, because
IMO user input and direct reactions to them should always have priority over any fancy feature
like syntax highlighting or showing symbols with LSP.

**Comment by fox0430** [comment]
Link #523
